import { NextConfig } from 'next';
import { withWorkflow } from 'workflow/next';

const nextConfig: NextConfig = {
  allowedDevOrigins: ['*.ngrok-free.app'],
  transpilePackages: [
    '@giveaway/account-context',
    '@giveaway/account-email',
    '@giveaway/account-history',
    '@giveaway/account-profile',
    '@giveaway/account-server',
    '@giveaway/account-settings',
    '@giveaway/allocation-model',
    '@giveaway/allocation-server',
    '@giveaway/app-config',
    '@giveaway/audience-server',
    '@giveaway/audience-table',
    '@giveaway/audience-user-details',
    '@giveaway/auth-actions',
    '@giveaway/auth-core',
    '@giveaway/auth-login-ui',
    '@giveaway/auth-model',
    '@giveaway/auth-provider-e2e',
    '@giveaway/auth-provider-inbound',
    '@giveaway/auth-server',
    '@giveaway/auth-session-ui',
    '@giveaway/automation-model',
    '@giveaway/automation-server',
    '@giveaway/automation-ui',
    '@giveaway/bluesky-api',
    '@giveaway/bluesky-connect',
    '@giveaway/bluesky-connect-ui',
    '@giveaway/bluesky-import',
    '@giveaway/bluesky-model',
    '@giveaway/bluesky-task-editor',
    '@giveaway/bluesky-task-entry',
    '@giveaway/bluesky-task-jobs',
    '@giveaway/bluesky-task-validation',
    '@giveaway/browse-list',
    '@giveaway/browse-server',
    '@giveaway/cache',
    '@giveaway/content-moderation',
    '@giveaway/custom-fields-model',
    '@giveaway/custom-fields-server',
    '@giveaway/custom-fields-ui',
    '@giveaway/db-client',
    '@giveaway/db-model',
    '@giveaway/db-schema',
    '@giveaway/discord-api',
    '@giveaway/discord-bot',
    '@giveaway/discord-connect',
    '@giveaway/discord-connect-ui',
    '@giveaway/discord-model',
    '@giveaway/discord-task-editor',
    '@giveaway/discord-task-entry',
    '@giveaway/discord-task-validation',
    '@giveaway/email',
    '@giveaway/feature-flags',
    '@giveaway/integration-icons',
    '@giveaway/integration-model',
    '@giveaway/integration-server',
    '@giveaway/integration-ui',
    '@giveaway/jobs',
    '@giveaway/kick-auth',
    '@giveaway/kick-task-editor',
    '@giveaway/kick-task-entry',
    '@giveaway/leaderboard-model',
    '@giveaway/leaderboard-server',
    '@giveaway/leaderboard-ui',
    '@giveaway/linkedin-task-editor',
    '@giveaway/linkedin-task-entry',
    '@giveaway/loyalty-model',
    '@giveaway/marketing-animations',
    '@giveaway/marketing-server',
    '@giveaway/marketing-ui',
    '@giveaway/meta-connect-ui',
    '@giveaway/meta-model',
    '@giveaway/meta-task-editor',
    '@giveaway/meta-task-entry',
    '@giveaway/onboarding',
    '@giveaway/participant-model',
    '@giveaway/participant-server',
    '@giveaway/participation-history-model',
    '@giveaway/participation-history-server',
    '@giveaway/participation-server',
    '@giveaway/picker-model',
    '@giveaway/picker-ui',
    '@giveaway/platform-catalog',
    '@giveaway/ratelimit',
    '@giveaway/referrals-model',
    '@giveaway/referrals-server',
    '@giveaway/request-context-model',
    '@giveaway/request-context-server',
    '@giveaway/rpc-client',
    '@giveaway/rpc-model',
    '@giveaway/rpc-server',
    '@giveaway/scoring-model',
    '@giveaway/scoring-server',
    '@giveaway/scoring-ui',
    '@giveaway/shell-footer',
    '@giveaway/shell-metrics',
    '@giveaway/shell-navigation',
    '@giveaway/shell-sidebar',
    '@giveaway/steam-auth',
    '@giveaway/steam-task-editor',
    '@giveaway/steam-task-entry',
    '@giveaway/steam-task-validation',
    '@giveaway/sweepstakes-access',
    '@giveaway/sweepstakes-actions-ui',
    '@giveaway/sweepstakes-dashboard',
    '@giveaway/sweepstakes-demo',
    '@giveaway/sweepstakes-details-analytics',
    '@giveaway/sweepstakes-details-entries',
    '@giveaway/sweepstakes-details-participants',
    '@giveaway/sweepstakes-details-promotion',
    '@giveaway/sweepstakes-details-shell',
    '@giveaway/sweepstakes-details-winners',
    '@giveaway/sweepstakes-editor-audience',
    '@giveaway/sweepstakes-editor-core',
    '@giveaway/sweepstakes-editor-design',
    '@giveaway/sweepstakes-editor-prizes',
    '@giveaway/sweepstakes-editor-selection',
    '@giveaway/sweepstakes-editor-server',
    '@giveaway/sweepstakes-editor-setup',
    '@giveaway/sweepstakes-insights-server',
    '@giveaway/sweepstakes-jobs',
    '@giveaway/sweepstakes-model',
    '@giveaway/sweepstakes-moderation-server',
    '@giveaway/sweepstakes-participation-core',
    '@giveaway/sweepstakes-participation-states',
    '@giveaway/sweepstakes-routes',
    '@giveaway/sweepstakes-ui',
    '@giveaway/sweepstakes-ui-testing',
    '@giveaway/task-actions',
    '@giveaway/task-editor',
    '@giveaway/task-editor-fields',
    '@giveaway/task-entry',
    '@giveaway/task-entry-core',
    '@giveaway/task-entry-form',
    '@giveaway/task-entry-referral',
    '@giveaway/task-entry-website',
    '@giveaway/task-jobs',
    '@giveaway/task-jobs-core',
    '@giveaway/task-model',
    '@giveaway/task-ui',
    '@giveaway/task-validation',
    '@giveaway/task-validation-core',
    '@giveaway/team-context',
    '@giveaway/team-invite-acceptance',
    '@giveaway/team-invites-server',
    '@giveaway/team-members-server',
    '@giveaway/team-members-ui',
    '@giveaway/team-model',
    '@giveaway/team-permissions',
    '@giveaway/team-picker',
    '@giveaway/team-server',
    '@giveaway/team-settings-integrations',
    '@giveaway/team-settings-profile',
    '@giveaway/team-settings-shell',
    '@giveaway/team-settings-socials',
    '@giveaway/team-testing',
    '@giveaway/templates-model',
    '@giveaway/templates-server',
    '@giveaway/theme-model',
    '@giveaway/theme-server',
    '@giveaway/tiktok-task-editor',
    '@giveaway/tiktok-task-entry',
    '@giveaway/turnstile-model',
    '@giveaway/turnstile-server',
    '@giveaway/turnstile-ui',
    '@giveaway/twitch-api',
    '@giveaway/twitch-bot',
    '@giveaway/twitch-connect',
    '@giveaway/twitch-connect-ui',
    '@giveaway/twitch-model',
    '@giveaway/twitch-task-editor',
    '@giveaway/twitch-task-entry',
    '@giveaway/twitch-task-validation',
    '@giveaway/ui-brand',
    '@giveaway/ui-carousel',
    '@giveaway/ui-charts',
    '@giveaway/ui-command',
    '@giveaway/ui-date',
    '@giveaway/ui-file-upload',
    '@giveaway/ui-hooks',
    '@giveaway/ui-layouts',
    '@giveaway/ui-primitives',
    '@giveaway/ui-qr',
    '@giveaway/ui-rich-text',
    '@giveaway/ui-theme',
    '@giveaway/ui-utils',
    '@giveaway/user-model',
    '@giveaway/user-quality-model',
    '@giveaway/user-quality-ui',
    '@giveaway/user-source-model',
    '@giveaway/user-source-ui',
    '@giveaway/util-browser',
    '@giveaway/util-collections',
    '@giveaway/util-errors',
    '@giveaway/util-geo',
    '@giveaway/util-html',
    '@giveaway/util-media',
    '@giveaway/util-random',
    '@giveaway/util-strings',
    '@giveaway/util-time',
    '@giveaway/util-types',
    '@giveaway/velora-api',
    '@giveaway/velora-auth',
    '@giveaway/velora-task-editor',
    '@giveaway/velora-task-entry',
    '@giveaway/velora-task-validation',
    '@giveaway/winners-model',
    '@giveaway/winners-server',
    '@giveaway/x-api',
    '@giveaway/x-connect',
    '@giveaway/x-import',
    '@giveaway/x-model',
    '@giveaway/x-picker-dashboard',
    '@giveaway/x-picker-editor',
    '@giveaway/x-picker-model',
    '@giveaway/x-picker-public',
    '@giveaway/x-picker-results',
    '@giveaway/x-picker-server',
    '@giveaway/x-picker-workflow',
    '@giveaway/x-scraper',
    '@giveaway/x-task-editor',
    '@giveaway/x-task-entry',
    '@giveaway/x-task-jobs',
    '@giveaway/youtube-model',
    '@giveaway/youtube-task-editor',
    '@giveaway/youtube-task-entry'
  ],
  experimental: {
    useCache: true
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com',
        search: ''
      },
      {
        protocol: 'https',
        hostname: '*.public.blob.vercel-storage.com',
        search: ''
      },
      {
        protocol: 'https',
        hostname: 'cdn.discordapp.com',
        search: ''
      },
      {
        protocol: 'https',
        hostname: 'pbs.twimg.com',
        search: ''
      },
      {
        protocol: 'https',
        hostname: 'pic.twitter.com',
        search: ''
      }
    ]
  }
};

export default withWorkflow(nextConfig);
