export const PRIVATE_STEAM_WISHLIST_ERROR = 'PRIVATE_STEAM_WISHLIST';
export const GAME_NOT_IN_WISHLIST_ERROR = 'GAME_NOT_IN_WISHLIST';
export const PRIVATE_STEAM_LIBRARY_ERROR = 'PRIVATE_STEAM_LIBRARY';
export const GAME_NOT_OWNED_ERROR = 'GAME_NOT_OWNED';
