import { SweepstakesTabSchema } from '@/schemas/sweepstakes';
import { UserDetailsTabSchema } from '@/schemas/user';
export const MAX_USER_TEAMS = 5;
export const DEFAULT_TEAM_LOGO = '🐶';
export const NEW_SWEEPSTAKE_THRESHOLD = 3;
export const ENDING_SOON_SWEEPSTAKE_THRESHOLD = 3;
export const STARTING_SOON_SWEEPSTAKE_THRESHOLD = 1;
export const UNKNOWN_USER_COUNTRY_CODE = 'unknown';
export const UNKNOWN_USER_AGENT = 'unknown';
export const UNKNOWN_ACCEPTED_LANGUAGE = 'en';
export const UNKNOWN_IP = '::1';
export const UNKNOWN_TIMEZONE = 'UTC';
export const UNKNOWN_SCREEN = '0x0';
export const DEFAULT_TIME_SERIES_DURATION = 7;
export const DEFAULT_PAGE_SIZE = 25;
export const DEFAULT_SWEEPSTAKES_DETAILS_TAB: SweepstakesTabSchema = 'preview';
export const DEFAULT_USER_DETAILS_TAB: UserDetailsTabSchema = 'overview';
export const UNKNOWN_USER_NAME = 'Unknown User';
export const DISCORD_INVITE_LINK = 'https://discord.gg/Ys8wW5w2Yt';
export const TWITTER_PROFILE_URL = 'https://x.com/TheGiveawayDog';
